const assert = require('node:assert/strict')
const { test } = require('node:test')

const upgrade = async (props) => {
	// Tests run against the local build generated by yarn test.
	// eslint-disable-next-line n/no-unpublished-import
	const { UpgradeScripts } = await import('../dist/upgrades.js')
	return UpgradeScripts[0]({ currentConfig: props.config || {} }, { secrets: null, feedbacks: [], ...props })
}
const tally = (id, options) => ({ id, controlId: 'bank:test', actionId: 'send_tally', options })

test('upgrades legacy connection and set/clear tally without changing credentials or other options', async () => {
	const config = { host: 'localhost', password: 'saved-password', apiKey: 'saved-key' }
	const actions = ['set', 'clear'].map((value) =>
		tally(value, { action: { isExpression: false, value }, userId: { isExpression: false, value: 42 } }),
	)
	const props = { config, actions, secrets: { password: 'saved-secret' } }
	const original = structuredClone(props)
	const result = await upgrade(props)
	assert.deepEqual(result.updatedConfig, { ...config, productionId: '' })
	assert.deepEqual(
		result.updatedActions,
		actions.map((action) => ({
			...action,
			options: { ...action.options, bus: { isExpression: false, value: 'pgm' } },
		})),
	)
	assert.equal(result.updatedSecrets, null)
	assert.deepEqual(result.updatedFeedbacks, [])
	assert.deepEqual(props, original)
	const repeated = await upgrade({ config: result.updatedConfig, actions: result.updatedActions })
	assert.equal(repeated.updatedConfig, null)
	assert.deepEqual(repeated.updatedActions, [])
})

test('preserves explicit productions, buses, expressions and unrelated actions', async () => {
	for (const productionId of ['', '42']) {
		const actions = [
			tally('pgm', { bus: { isExpression: false, value: 'pgm' } }),
			tally('prv', { bus: { isExpression: false, value: 'prv' } }),
			tally('expression', { bus: { isExpression: true, value: '$(custom:bus)' } }),
			{ ...tally('other', {}), actionId: 'send_talk' },
		]
		const props = { config: { productionId }, actions }
		const original = structuredClone(props)
		const result = await upgrade(props)
		assert.equal(result.updatedConfig, null)
		assert.deepEqual(result.updatedActions, [])
		assert.deepEqual(props, original)
	}
})

test('upgrades imported actions without a connection config', async () => {
	const result = await upgrade({ config: null, actions: [tally('imported', {})] })
	assert.equal(result.updatedConfig, null)
	assert.deepEqual(result.updatedActions[0].options.bus, { isExpression: false, value: 'pgm' })
})

test('upgrades config independently of actions', async () => {
	assert.deepEqual((await upgrade({ config: { host: 'localhost' }, actions: [] })).updatedConfig, {
		host: 'localhost',
		productionId: '',
	})
})
